stages:
- name: Compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: RKN
      pushRemote: true
      registry: 127.0.0.1:34514
timeout: 60
notification: {}
