version: '3.4'

services:
  rkn:
    build: ./rkn/
    restart: always
    container_name: rkn
    volumes:
      - /opt/data/rkn:/home/zapret
  mysql:
    image: "mysql:5.7"
    command: --init-file /data/application/init.sql
    volumes:
      - ./sql/init.sql:/data/application/init.sql
      - /opt/data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "n95ow4"
      MYSQL_DATABASE: "rkn"
      MYSQL_USER: "serg470"
      MYSQL_PASSWORD: "n95ow4"
    ports:
      - "0.0.0.0:3306:3306"
  web:
    build: ./nginx/
#    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx/web:/var/www/
    ports:
      - 80:80
    links:
      - php
  php:
    build: ./php/
    image: php:7.2-fpm
    restart: always
    container_name: php7.2
    ports: 
      - 9000:9000
    volumes:
      - ./nginx/web:/var/www
      - ./php/php.ini:/usr/local/etc/php.ini