CREATE DATABASE IF NOT EXISTS rkn;
USE rkn;
CREATE TABLE IF NOT EXISTS `domain` (`domain` text NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS `ip_addresses` (`ip` varchar(40) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE USER 'serg'@'localhost' IDENTIFIED BY 'n95ow4';
GRANT ALL PRIVILEGES ON *.* TO 'serg'@'localhost' WITH GRANT OPTION;
CREATE USER 'serg'@'%' IDENTIFIED BY 'n95ow4';
GRANT ALL PRIVILEGES ON *.* TO 'serg'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;